export const PORTFOLIO_ITEMS = [
  {
    company: "VMEX Finance",
    link: "vmex.finance",
    img: "/img/companies/vmex-logo.svg",
    preview: ["/img/companies/Vmex-Finance-pic1.png", "/img/companies/Vmex-Finance-pic2.png", "/img/companies/Vmex-Finance-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "VMEX Finance provides decentralized, next-generation liquidity markets.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain"
  },
  {
    company: "Raycon",
    link: "rayconglobal.com",
    img: "/img/companies/raycon-logo(1).png",
    preview: ["/img/companies/raycon-pic1.png","/img/companies/raycon-pic2.png","/img/companies/raycon-pic3.png"],
    languages: "Javascript, React, Shopify, HTML, CSS",
    about: "Raycon is an innovative sound system company, specializing in headphones.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Ecommerce",
    padding: 'p-4'
  },
  {
    company: "zeroDAO",
    link: "zerodao.com",
    img: "/img/companies/ZD-logo-3d.png",
    preview: ["/img/companies/zerodao-pic1.png","/img/companies/zerodao-pic2.png","/img/companies/zerodao-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "zeroDAO is the decentralized governor of the ZERO network, enabling cross-chain messaging for trade or even more complex scripting.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain"
  },
  {
    company: "Papes",
    link: "papes.xyz",
    img: "/img/companies/papes-logo.svg",
    preview: ["/img/companies/papes-pic1.png","/img/companies/papes-pic2.png","/img/companies/papes-pic3.png"],
    languages: "NextJS, Solidity, Typescript",
    about: "Papes XYZ is a premium Bored Apes Yacht Club exclusive brand selling rolling papers.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain",
    padding: 'p-0'
  },
  {
    company: "DataEarn",
    link: "app.dataearn.com",
    img: "/img/companies/dataearn-logo(1).png",
    preview: ["/img/companies/dataearn-pic1.png","/img/companies/dataearn-pic2.png","/img/companies/dataearn-pic3.png"],
    languages: "NextTS, Python, Django, SQL",
    about: "DataEarn is building a way to allow individuals to access, understand, protect, and monetize their data.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Web App",
    padding: 'p-6'
  },
  {
    company: "Vita Films",
    link: "vitafilmllc.com",
    img: "/img/companies/vita-logo.png",
    preview: ["/img/companies/vita-pic1.png","/img/companies/vita-pic2.png","/img/companies/vita-pic3.png"],
    languages: "Nextjs, CSS",
    about: "Vita Film is a videography and media company specializing in outdoor, wedding, and commercial spaces.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Website",
    padding: 'p-4'
  },
  {
    company: "PintSwap",
    link: "pintswap.eth.limo",
    img: "/img/companies/pintswap-logo.png",
    preview: ["/img/companies/pintswap-pic1.png","/img/companies/pintswap-pic2.png","/img/companies/pintswap-pic3.png"],
    languages: "NextJS, LibP2P, Solidity, Typescript",
    about: "PintSwap is a peer-to-peer decentralized exchange using multi-party transaction scripts.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain",
    padding: 'p-4'
  },
  {
    company: "Bonanza Exorsa",
    link: "bonanzaexorsa.com",
    img: "/img/companies/bonanza-3d-logo.png",
    preview: ["/img/companies/bonanza-pic1.png","/img/companies/bonanza-3d-logo.png","/img/companies/bonanza-pic1.png"],
    languages: "NextTS, Solidity, Typescript",
    about: "Bonanza Exorsa is a metaphysical brand using NFT's.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain",
    padding: 'p-4'
  },
  {
    company: "Marmolaz",
    link: "marmolaz.com",
    img: "/img/companies/marmolaz-logo.png",
    preview: ["/img/companies/marmolaz-pic1.png","/img/companies/marmolaz-pic2.png","/img/companies/marmolaz-pic3.png"],
    languages: "Shopify",
    about: "Marmolaz creates natural, lime-based, construction products.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Ecommerce",
    padding: 'p-4'
  },
  {
    company: "LiveDuel",
    link: "liveduel.com",
    img: "/img/companies/liveduel-logo.png",
    preview: ["/img/companies/liveduel-pic1.png","/img/companies/liveduel-pic2.png","/img/companies/liveduel-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "LiveDuel combines live streaming and interactive content like our prediction exchange and live trivia game show using blockchain technology.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain",
    padding: 'p-2'
  },
  {
    company: "Lazar Stucco",
    link: "lazarstucco.com",
    img: "/img/companies/lazar-logo.png",
    preview: ["/img/companies/lazarstucco-pic1.png","/img/companies/lazarstucco-pic2.png","/img/companies/lazarstucco-pic3.png"],
    languages: "HTML, CSS",
    about: "Lazar Stucco is an experienced contractor working with European Stucco for residential and commercial construction. ",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Website",
    padding: 'p-4'
  },
  {
    company: "Fellowship Event Hall",
    link: "events.saintmaryro.org",
    img: "/img/companies/fellowship-logo.png",
    preview: ["/img/companies/fellowship-pic1.png","/img/companies/fellowship-pic2.png","/img/companies/fellowship-pic3.png"],
    languages: "NextJS, SendGrid, Typescript",
    about: "Fellowship Event Hall is an event hall in Georgia hosting various celebrations and activities.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Website",
    padding: 'p-4'
  },
  {
    company: "Sports Roulette ATL",
    link: "sportsrouletteatl.com",
    img: "/img/companies/sra-logo.png",
    preview: ["/img/companies/sportsrouletteatl-pic1.png","/img/companies/sportsrouletteatl-pic2.png","/img/companies/sportsrouletteatl-pic3.png"],
    languages: "NextJS, TailwindCSS, Typescript",
    about: "Sports Roulette ATL is a fun sports league for adults looking to casually network.",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Website"
  },
  {
    company:"Pepe Analytics",
    link:"https://pepeanalytics.com/",
    img:"/img/companies/pepeanalytics-logo.png",
    preview:["/img/companies/pepeanalytics-pic1.png","/img/companies/pepeanalytics-pic2.png","/img/companies/pepeanalytics-pic3.png"],
    languages:"",
    aout:"",
    goals: null,
    challenges: null,
    conclusion: null,
    type: "Blockchain"
  }
]