export const PORTFOLIO_ITEMS = [
  {
    company: "PintSwap",
    link: "pintswap.exchange",
    img: "/img/companies/ps-cup.svg",
    preview: ["/img/companies/pintswap-pic1.png","/img/companies/pintswap-pic2.png","/img/companies/pintswap-pic3.png"],
    languages: "NextJS, LibP2P, Solidity, Typescript",
    about: "PintSwap is a peer-to-peer decentralized exchange using multi-party transaction scripts.",
    goals: "Trade low-liquidity tokens without the risk of losing funds to high slippage while also avoiding any unnecessary fees. To do this, build a PWA, Telegram Bot, and trading engine to automate processes all on top of a peer-to-peer network.", 
    challenges: "Creating token swapping contracts is easy. But, creating a transaction script with 2p-ecdsa to enable OTC-type trading and reliably connecting all that to multiple clients is not. We decided to create a LibP2P wrapper to run in any environment, including browsers, with WebRTC as the communication protocol combined with websockets to enable high throughput of data being sent.",
    conclusion: "Peer-to-peer networks are very powerful. Combined with the revolutionary blockchain, we were able to build an optimized P2P OTC orderbook DEX, removing the issues traditional AMM's have.",
    type: "Blockchain",
    padding: 'px-6'
  },
  {
    company: "VMEX Finance",
    link: "vmex.finance",
    img: "/img/companies/vmex-logo.svg",
    preview: ["/img/companies/Vmex-Finance-pic1.png", "/img/companies/Vmex-Finance-pic2.png", "/img/companies/Vmex-Finance-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "VMEX Finance provides decentralized, next-generation liquidity markets.",
    goals: "Enable deeper liquidity in the lending and borrowing crypto markets. Create the same trustworthy user experience while also giving crypto users more opportunities to utilize all their tokens.",
    challenges: "While many lending and borrowing protocols have been built, not many have been created with the idea that some protocols/tokens fail in one way or another. How can we give trust back to the users in the world of decentralized finance?",
    conclusion: "The concept of tranches is used in traditional finance, so we decided to build a lending and borrowing protocol that is effectively the same thing. This way, you have the same familiar defi experience with the additional comfort that even if one market fails, your funds don't take the same impact.",
    type: "Blockchain"
  },
  {
    company: "Raycon",
    link: "rayconglobal.com",
    img: "/img/companies/raycon-logo(1).png",
    preview: ["/img/companies/raycon-pic1.png","/img/companies/raycon-pic2.png","/img/companies/raycon-pic3.png"],
    languages: "Javascript, React, Shopify, HTML, CSS",
    about: "Raycon is an innovative sound system company, specializing in headphones.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Ecommerce",
    padding: 'px-6'
  },
  {
    company: "zeroDAO",
    link: "zerodao.com",
    img: "/img/companies/ZD-logo-3d.png",
    preview: ["/img/companies/zerodao-pic1.png","/img/companies/zerodao-pic2.png","/img/companies/zerodao-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "zeroDAO is the decentralized governor of the ZERO network, enabling cross-chain messaging for trade or even more complex scripting.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Blockchain"
  },
  {
    company: "DataEarn",
    link: "app.dataearn.com",
    img: "/img/companies/dataearn-logo(1).png",
    preview: ["/img/companies/dataearn-pic1.png","/img/companies/dataearn-pic2.png","/img/companies/dataearn-pic3.png"],
    languages: "NextTS, Python, Django, SQL",
    about: "DataEarn is building a way to allow individuals to access, understand, protect, and monetize their data.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Web App",
    padding: 'px-6'
  },
  {
    company: "Papes",
    link: "papes.xyz",
    img: "/img/companies/papes-logo.svg",
    preview: ["/img/companies/papes-pic1.png","/img/companies/papes-pic2.png","/img/companies/papes-pic3.png"],
    languages: "NextJS, Solidity, Typescript",
    about: "Papes XYZ is a premium Bored Apes Yacht Club exclusive brand selling rolling papers.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Blockchain",
    padding: 'p-0'
  },
  {
    company: "Vita Films",
    link: "vitafilmllc.com",
    img: "/img/companies/vita-logo.png",
    preview: ["/img/companies/vita-pic1.png","/img/companies/vita-pic2.png","/img/companies/vita-pic3.png"],
    languages: "Nextjs, CSS",
    about: "Vita Film is a videography and media company specializing in outdoor, wedding, and commercial spaces.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Website",
    padding: 'px-4'
  },
  {
    company:"Pepe Analytics",
    link:"https://pepeanalytics.com/",
    img:"/img/companies/pepeanalytics-logo.png",
    preview:["/img/companies/pepeanalytics-pic1.png","/img/companies/pepeanalytics-pic2.png","/img/companies/pepeanalytics-pic3.png"],
    languages:"",
    aout:"",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Blockchain",
    padding: 'px-2'
  },
  {
    company: "Bonanza Exorsa",
    link: "bonanzaexorsa.com",
    img: "/img/companies/bonanza-3d-logo.png",
    preview: ["/img/companies/bonanza-pic1.png","/img/companies/bonanza-3d-logo.png","/img/companies/bonanza-pic1.png"],
    languages: "NextTS, Solidity, Typescript",
    about: "Bonanza Exorsa is a metaphysical brand using NFT's.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Blockchain",
    padding: 'px-4'
  },
  {
    company: "Marmolaz",
    link: "marmolaz.com",
    img: "/img/companies/marmolaz-logo.png",
    preview: ["/img/companies/marmolaz-pic1.png","/img/companies/marmolaz-pic2.png","/img/companies/marmolaz-pic3.png"],
    languages: "Shopify",
    about: "Marmolaz creates natural, lime-based, construction products.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Ecommerce",
    padding: 'px-4'
  },
  {
    company: "LiveDuel",
    link: "liveduel.com",
    img: "/img/companies/liveduel-logo.png",
    preview: ["/img/companies/liveduel-pic1.png","/img/companies/liveduel-pic2.png","/img/companies/liveduel-pic3.png"],
    languages: "NextTS, Solidity, Typescript, SQL",
    about: "LiveDuel combines live streaming and interactive content like our prediction exchange and live trivia game show using blockchain technology.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Blockchain",
    padding: 'px-2'
  },
  {
    company: "Lazar Stucco",
    link: "lazarstucco.com",
    img: "/img/companies/lazar-logo.png",
    preview: ["/img/companies/lazarstucco-pic1.png","/img/companies/lazarstucco-pic2.png","/img/companies/lazarstucco-pic3.png"],
    languages: "HTML, CSS",
    about: "Lazar Stucco is an experienced contractor working with European Stucco for residential and commercial construction. ",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Website",
    padding: 'px-4'
  },
  {
    company: "Fellowship Events",
    link: "events.saintmaryro.org",
    img: "/img/companies/fellowship-logo.png",
    preview: ["/img/companies/fellowship-pic1.png","/img/companies/fellowship-pic2.png","/img/companies/fellowship-pic3.png"],
    languages: "NextJS, SendGrid, Typescript",
    about: "Fellowship Event Hall is an event hall in Georgia hosting various celebrations and activities.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Website",
    padding: 'px-4'
  },
  {
    company: "Sports Roulette ATL",
    link: "sportsrouletteatl.com",
    img: "/img/companies/sra-logo.png",
    preview: ["/img/companies/sportsrouletteatl-pic1.png","/img/companies/sportsrouletteatl-pic2.png","/img/companies/sportsrouletteatl-pic3.png"],
    languages: "NextJS, TailwindCSS, Typescript",
    about: "Sports Roulette ATL is a fun sports league for adults looking to casually network.",
    goals: "",
    challenges: "",
    conclusion: "",
    type: "Website"
  },
]